#!/usr/bin/env python3
"""Build the synthetic Russian AR acceptance corpus and its expected-issues manifest.

    python3 tools/fixtures/build_ar_corpus.py           # write the corpus
    python3 tools/fixtures/build_ar_corpus.py --check   # verify, write nothing

`--check` rebuilds every artefact in memory and compares it byte-for-byte with what is
committed, then re-runs every oracle assertion *against the committed files* rather than
against the fresh build. Verifying the thing in your hand and verifying the thing on disk
are different claims, and only the second one is what other lanes will consume.

What the build refuses to do:

*   write if any line would overflow the text box, because a reader could then split a
    quotation across reconstructed lines;
*   write if a quotation is not a substring of exactly one line on its declared page;
*   write if a quotation is not recoverable character-for-character from the text
    extracted back out of the generated bytes, at exactly the pages it declares and no
    others;
*   write if the baseline falls outside the PC-01 envelope, or if any negative fixture
    violates anything other than the single rule it is named for.

That last set is the point of the whole task. The manifest is the acceptance oracle for
the programme: in Gate B a grounding gate rejects any model finding whose quotation does
not resolve at its declared anchor, so a quotation that is not actually in the text layer
would contaminate every downstream measurement silently.

Pure standard library. The repository lock carries no PDF library and is a single-owner
hotspot this session does not own.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from ar_corpus import content, document, envelope, negatives, pdfextract, pdfwrite  # noqa: E402
from ar_corpus import ttfsubset  # noqa: E402

REPO_ROOT = Path(__file__).resolve().parents[2]
FONT_ASSET = REPO_ROOT / "tools" / "fixtures" / "assets" / "ARCorpusSans.ttf"
OUT_DIR = REPO_ROOT / "fixtures" / "synthetic" / "ar"
NEGATIVE_DIR = OUT_DIR / "negative"

BASELINE_NAME = "ar_baseline.pdf"
MANIFEST_NAME = "expected_issues.json"
CHECKSUM_NAME = "SHA256SUMS"

MANIFEST_SCHEMA = "ar-expected-issues/1"


class BuildError(RuntimeError):
    """An invariant the corpus is not allowed to be written without."""


def load_font() -> pdfwrite.EmbeddedFont:
    """Build the embedded font from the committed subset, never from a system font."""
    if not FONT_ASSET.is_file():
        raise BuildError(
            f"missing font subset {FONT_ASSET}. Rebuild it with "
            "tools/fixtures/build_font_subset.py"
        )
    raw = FONT_ASSET.read_bytes()
    metrics = ttfsubset.read(raw)
    missing = sorted(set(content.character_set()) - set(metrics.char_to_gid))
    if missing:
        raise BuildError(
            f"the committed font subset has no glyph for {''.join(missing)!r}. "
            "Rerun tools/fixtures/build_font_subset.py after changing the text."
        )
    return pdfwrite.EmbeddedFont(
        font_bytes=raw,
        units_per_em=metrics.units_per_em,
        char_to_gid=metrics.char_to_gid,
        gid_advance=metrics.gid_advance,
        ascent=metrics.ascent,
        descent=metrics.descent,
        cap_height=metrics.cap_height,
        bbox=metrics.bbox,
    )


def sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


# --------------------------------------------------------------------------------------
# Oracle verification
# --------------------------------------------------------------------------------------


def verify_source_placement() -> list[str]:
    """Every quotation is a substring of exactly one authored line on its declared page."""
    problems: list[str] = []
    for owner, page_number, quotation in content.all_quotations():
        page = content.PAGES[page_number - 1]
        hits = [line.text for line in page.lines if quotation in line.text]
        if len(hits) != 1:
            problems.append(
                f"{owner}: quotation {quotation!r} matches {len(hits)} authored lines on "
                f"page {page_number}, expected exactly 1"
            )
    return problems


def verify_extracted(pages: list[str]) -> list[str]:
    """The load-bearing check: quotations survive the round trip through the PDF bytes.

    Character-for-character, at exactly the declared pages and nowhere else. The
    "nowhere else" half matters as much as the first: a quotation that also appears on an
    undeclared page would make the grounding anchor ambiguous, and a finding could then
    be "grounded" against a page nobody meant.
    """
    problems: list[str] = []
    if len(pages) != len(content.PAGES):
        problems.append(
            f"extracted {len(pages)} pages, the document declares {len(content.PAGES)}"
        )
        return problems

    declared: dict[str, set[int]] = {}
    for _owner, page_number, quotation in content.all_quotations():
        declared.setdefault(quotation, set()).add(page_number)

    for quotation, declared_pages in sorted(declared.items()):
        found = {n for n, text in enumerate(pages, start=1) if quotation in text}
        if found != declared_pages:
            problems.append(
                f"quotation {quotation!r}: declared on pages {sorted(declared_pages)}, "
                f"found on pages {sorted(found)}"
            )
    return problems


def verify_envelope(baseline: bytes) -> list[str]:
    report = envelope.check(baseline)
    if report.accepted:
        return []
    return [
        f"baseline violates {r.rule} ({r.status.value}): {r.detail}"
        for r in report.results if r.status is not envelope.Status.PASS
    ]


def verify_negatives(fixtures: list[negatives.NegativeFixture]) -> list[str]:
    """Each negative violates exactly the single rule it is named for."""
    problems: list[str] = []
    for fixture in fixtures:
        report = envelope.check(fixture.data)
        if report.violations != (fixture.violates,):
            problems.append(
                f"{fixture.filename}: expected to violate exactly {fixture.violates}, "
                f"violates {list(report.violations)}"
            )
        # A rule that could not be evaluated must never be reported as passing; assert
        # that the fixture's own rule is genuinely evaluated rather than skipped.
        if fixture.violates in report.not_evaluated:
            problems.append(
                f"{fixture.filename}: {fixture.violates} was not evaluated at all, so "
                "the fixture proves nothing about it"
            )
    return problems


# --------------------------------------------------------------------------------------
# Manifest
# --------------------------------------------------------------------------------------


def _anchor(pages: list[str], page_number: int, quotation: str) -> dict[str, object]:
    """Locate a quotation inside the extracted page text, for the grounding gate."""
    text = pages[page_number - 1]
    offset = text.find(quotation)
    if offset < 0:
        raise BuildError(f"quotation {quotation!r} is not on page {page_number}")
    lines = text.split("\n")
    consumed = 0
    line_index = 0
    for index, line in enumerate(lines):
        if consumed <= offset < consumed + len(line) + 1:
            line_index = index
            break
        consumed += len(line) + 1
    return {
        "page": page_number,
        "quotation": quotation,
        "char_offset_in_page_text": offset,
        "line_index_in_page_text": line_index,
        "line_text": lines[line_index],
    }


def build_manifest(
    baseline: bytes,
    pages: list[str],
    fixtures: list[negatives.NegativeFixture],
) -> dict[str, object]:
    return {
        "schema": MANIFEST_SCHEMA,
        "synthetic": True,
        "notice": (
            "Synthetic corpus. No customer, production or real project bytes, and no "
            "real organisation, address or person. Owner decision OD-17 rules the PC-01 "
            "corpus synthetic-only."
        ),
        "generated_by": "tools/fixtures/build_ar_corpus.py",
        "regenerate": "python3 tools/fixtures/build_ar_corpus.py",
        "verify": "python3 tools/fixtures/build_ar_corpus.py --check",
        "text_extraction": (
            "Quotation offsets are into the text of a single page as produced by "
            "tools/fixtures/ar_corpus/pdfextract.py: runs grouped into lines by "
            "baseline, lines top to bottom, joined by a single newline. Every quotation "
            "lies wholly within one line, so any extractor that preserves line content "
            "resolves it identically."
        ),
        "envelope": {
            "max_bytes": envelope.MAX_BYTES,
            "max_pages": envelope.MAX_PAGES,
            "rules": {rule: envelope.RULE_DESCRIPTIONS[rule] for rule in envelope.RULES},
        },
        "baseline": {
            "path": f"fixtures/synthetic/ar/{BASELINE_NAME}",
            "sha256": sha256(baseline),
            "bytes": len(baseline),
            "pages": len(pages),
            "language": "ru",
            "discipline": "AR",
            "page_text_sha256": [
                sha256(text.encode("utf-8")) for text in pages
            ],
        },
        "categories": [content.CATEGORY_CONTRADICTION, content.CATEGORY_PLACEHOLDER],
        "seeded_issue_count": len(content.SEEDED_ISSUES),
        "seeded_issues": [
            {
                "id": issue.id,
                "category": issue.category,
                "attribute": issue.attribute,
                "pages": sorted({ev.page for ev in issue.evidence}),
                "summary_ru": issue.summary,
                "evidence": [
                    _anchor(pages, ev.page, ev.quotation) for ev in issue.evidence
                ],
            }
            for issue in content.SEEDED_ISSUES
        ],
        "controls": [
            {
                "id": control.id,
                "pages": list(control.pages),
                "quotation": control.quotation,
                "would_be_false_positive_as": control.would_be_false_positive_as,
                "why_not_an_issue_ru": control.why_not_an_issue,
                "anchors": [
                    _anchor(pages, page, control.quotation) for page in control.pages
                ],
            }
            for control in content.CONTROLS
        ],
        "negative_fixtures": [
            {
                "name": fixture.name,
                "path": f"fixtures/synthetic/ar/negative/{fixture.filename}",
                "violates_rule": fixture.violates,
                "rule_description": envelope.RULE_DESCRIPTIONS[fixture.violates],
                "sha256": sha256(fixture.data),
                "bytes": len(fixture.data),
                "description": fixture.description,
            }
            for fixture in fixtures
        ],
    }


def manifest_bytes(manifest: dict[str, object]) -> bytes:
    return (
        json.dumps(manifest, ensure_ascii=False, indent=2, sort_keys=False) + "\n"
    ).encode("utf-8")


def checksum_bytes(entries: list[tuple[str, bytes]]) -> bytes:
    lines = [f"{sha256(data)}  {name}" for name, data in entries]
    return ("\n".join(lines) + "\n").encode("utf-8")


# --------------------------------------------------------------------------------------
# Build
# --------------------------------------------------------------------------------------


def build_all() -> list[tuple[Path, bytes]]:
    """Build every artefact, verifying every invariant before returning anything."""
    font = load_font()

    problems = verify_source_placement()
    if problems:
        raise BuildError("quotation placement:\n  " + "\n  ".join(problems))

    baseline = document.build_baseline(font)
    pages = pdfextract.extract_pages(baseline)

    problems = verify_extracted(pages)
    if problems:
        raise BuildError(
            "the text layer does not carry the manifest quotations:\n  "
            + "\n  ".join(problems)
        )

    problems = verify_envelope(baseline)
    if problems:
        raise BuildError("baseline envelope:\n  " + "\n  ".join(problems))

    fixtures = negatives.build_all(font)
    problems = verify_negatives(fixtures)
    if problems:
        raise BuildError("negative fixtures:\n  " + "\n  ".join(problems))

    manifest = build_manifest(baseline, pages, fixtures)

    artefacts: list[tuple[Path, bytes]] = [
        (OUT_DIR / BASELINE_NAME, baseline),
        (OUT_DIR / MANIFEST_NAME, manifest_bytes(manifest)),
    ]
    artefacts += [(NEGATIVE_DIR / f.filename, f.data) for f in fixtures]

    checksums = checksum_bytes([
        (str(path.relative_to(OUT_DIR)), data) for path, data in artefacts
    ])
    artefacts.append((OUT_DIR / CHECKSUM_NAME, checksums))
    return artefacts


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Build the synthetic AR corpus.")
    parser.add_argument(
        "--check", action="store_true",
        help="verify the committed corpus against a fresh build; write nothing",
    )
    args = parser.parse_args(argv)

    try:
        artefacts = build_all()
    except (BuildError, ValueError, KeyError) as exc:
        print(f"FAIL: {exc}", file=sys.stderr)
        return 1

    if args.check:
        failures: list[str] = []
        for path, data in artefacts:
            rel = path.relative_to(REPO_ROOT)
            if not path.is_file():
                failures.append(f"{rel}: missing")
                continue
            committed = path.read_bytes()
            if committed != data:
                failures.append(
                    f"{rel}: committed sha256 {sha256(committed)} "
                    f"({len(committed)} bytes) != rebuilt sha256 {sha256(data)} "
                    f"({len(data)} bytes)"
                )

        # Re-run the oracle against what is on disk, not only against the fresh build.
        baseline_path = OUT_DIR / BASELINE_NAME
        if baseline_path.is_file():
            committed_pages = pdfextract.extract_pages(baseline_path.read_bytes())
            failures += [f"committed baseline: {p}" for p in verify_extracted(committed_pages)]
            failures += [
                f"committed baseline: {p}"
                for p in verify_envelope(baseline_path.read_bytes())
            ]

        if failures:
            print("FAIL: the committed corpus does not match a fresh build:",
                  file=sys.stderr)
            for failure in failures:
                print(f"  {failure}", file=sys.stderr)
            return 1
        for path, data in artefacts:
            print(f"OK  {path.relative_to(REPO_ROOT)}  {sha256(data)}  {len(data)} bytes")
        return 0

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    NEGATIVE_DIR.mkdir(parents=True, exist_ok=True)
    for path, data in artefacts:
        path.write_bytes(data)
        print(f"wrote {path.relative_to(REPO_ROOT)}  {sha256(data)}  {len(data)} bytes")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
