"""P02 head: the complete PC-01 schema, with its invariants as database constraints.

This is the only migration that creates a product table, and it creates all of them
at once. The plan gives every Gate B session one frozen head to build against, so a
schema need arriving later is a request to this seam - a test plus the constraint it
wants - and never a second head.

Why the DDL is written out rather than autogenerated: the invariants that carry this
schema are not column types. They are append-only ledgers, immutable published rows
and a declared state topology, all of which live in triggers and CHECK constraints
that autogenerate does not write and does not notice going missing.

What is encoded here, and where it comes from:

* ``contracts/domain/v1/identifiers.json`` - the identifier format, as a CHECK on
  every identity column. An identifier failing the contract pattern is rejected by
  the database as well as by the value type, so a raw-SQL writer cannot bypass it.
  Nothing in this schema uses a path, an object key, a file name, a checksum or a
  display ordinal as a key: those columns exist, are named for what they are and are
  referenced by no foreign key.
* ``contracts/domain/v1/state-machines.json`` - the declared topology of the three
  machines PC-01 instantiates (``audit_run``, ``blob``, ``command_idempotency``),
  seeded as data into ``contract_state_transition`` and enforced by one trigger. An
  undeclared edge raises SQLSTATE ``AM001``; there is no permissive default.
  ``import``, ``job`` and ``attempt`` are not instantiated: PC-01 has no Import, no
  Job and no Attempt, so no table, no state column and no conformance claim.
* ``contracts/analysis/v1/stage-registry.json`` - the nine canonical stage ids and
  the four StageResult statuses, and the rule that a ``succeeded`` result carries no
  error.
* ``contracts/domain/v1/error-codes.json`` - the closed twenty-code catalog, as the
  domain of every column that records a typed failure.
* ``OD-12`` - the decision author identity is one configured local reviewer label,
  persisted server-side with each event. That is the ``author_label`` column, and
  deciding it later would have been a schema change.

Deliberately absent: job, attempt, lease, export, import, comparison, norms and
knowledge-base tables. PC-01 instantiates none of those aggregates, and the CSV
export is computed on request rather than stored.

Revision ID: 0002_pc01_schema
Revises: 0001_baseline
Created: 2026-09-10
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op

revision: str = "0002_pc01_schema"
down_revision: str | None = "0001_baseline"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# ---------------------------------------------------------------------------
# Shared fragments
# ---------------------------------------------------------------------------

# The contract's pattern_template, instantiated per prefix. Kept as a literal here
# rather than imported from auditmanager.shared.identity, because a migration that
# imports application code changes meaning when that code changes. The agreement
# between the two is asserted by tests/contract/domain_p02/test_identifier_catalog.py.
ULID_BODY = "[0-9A-HJKMNP-TV-Z]{26}"


def id_check(column: str, prefix: str) -> str:
    return f"{column} ~ '^{prefix}_{ULID_BODY}$'"


SHA256 = "~ '^[0-9a-f]{64}$'"

# The closed error catalog. Every column recording a typed failure draws from it.
ERROR_CODES = (
    "validation_failed",
    "not_found",
    "authentication_required",
    "permission_denied",
    "conflict",
    "state_transition_not_allowed",
    "idempotency_key_reuse",
    "idempotency_key_in_progress",
    "idempotency_key_stale",
    "unsupported_contract_version",
    "storage_integrity_error",
    "dependency_unavailable",
    "dependency_credential_refused",
    "staged_upload_lost",
    "required_norm_unavailable",
    "analysis_input_invalid",
    "analysis_failed",
    "partial_result_not_publishable",
    "cost_budget_exceeded",
    "stale_attempt",
    "execution_token_invalid",
    "internal_error",
)

# The nine canonical stages of the analysis registry. PC-01 executes four of them;
# the domain of the column is the whole registry so a later slice adds no migration.
STAGE_IDS = (
    "source_preparation",
    "page_geometry_extraction",
    "document_context_build",
    "text_analysis",
    "block_analysis",
    "finding_merge",
    "finding_review",
    "finding_correction",
    "norm_verification",
)

# audit_run has no `succeeded`: that is a StageResult status on a different
# aggregate. The success terminal of a run is `published`.
RUN_STATES = (
    "created",
    "queued",
    "running",
    "validating",
    "published",
    "partial",
    "failed",
    "cancelled",
)

BLOB_STATES = (
    "temporary",
    "verifying",
    "available",
    "rejected",
    "erasure_pending",
    "erased",
)

COMMAND_STATES = ("in_progress", "succeeded", "failed", "abandoned")

STAGE_STATUSES = ("succeeded", "partial", "failed", "skipped")

FINDING_CATEGORIES = ("internal_contradiction", "explicit_placeholder")

PROVIDER_MODES = ("live", "recorded")

DECISION_EVENT_TYPES = ("accept", "reject", "comment", "revoke")

# The closed projection enum. PC-01 produces `pending`, `accepted` and `rejected`;
# `needs_manual_review` is declared with no PC-01 producer, recorded in
# docs/program/P02_SEAMS.md alongside the unallocated identifiers.
VERDICTS = ("pending", "accepted", "rejected", "needs_manual_review")

# The declared topology of the three machines PC-01 instantiates. A NULL from_state
# is the machine's initial state: the only state an INSERT may create.
STATE_TOPOLOGY: tuple[tuple[str, str | None, str], ...] = (
    ("audit_run", None, "created"),
    ("audit_run", "created", "queued"),
    ("audit_run", "created", "cancelled"),
    ("audit_run", "queued", "running"),
    ("audit_run", "queued", "cancelled"),
    ("audit_run", "queued", "failed"),
    ("audit_run", "running", "validating"),
    ("audit_run", "running", "failed"),
    ("audit_run", "running", "cancelled"),
    ("audit_run", "validating", "published"),
    ("audit_run", "validating", "partial"),
    ("audit_run", "validating", "failed"),
    ("blob", None, "temporary"),
    ("blob", "temporary", "verifying"),
    ("blob", "temporary", "rejected"),
    ("blob", "verifying", "available"),
    ("blob", "verifying", "rejected"),
    ("blob", "available", "erasure_pending"),
    ("blob", "erasure_pending", "erased"),
    ("blob", "erasure_pending", "available"),
    ("command_idempotency", None, "in_progress"),
    ("command_idempotency", "in_progress", "succeeded"),
    ("command_idempotency", "in_progress", "failed"),
    ("command_idempotency", "in_progress", "abandoned"),
)


def enum_check(column: str, values: Sequence[str]) -> str:
    rendered = ", ".join(f"'{value}'" for value in values)
    return f"{column} IN ({rendered})"


def upgrade() -> None:
    _create_guard_functions()
    _create_contract_topology()
    _create_project_and_documents()
    _create_blobs_and_manifest()
    _create_runs_and_commands()
    _create_findings()
    _create_ledgers()
    _create_projection_view()
    _attach_guards()


# ---------------------------------------------------------------------------
# 1. Guard functions
# ---------------------------------------------------------------------------


def _create_guard_functions() -> None:
    # Append-only ledger: no UPDATE, no DELETE, ever. The frozen catalog names this
    # case under state_transition_not_allowed - "delete a decision event".
    op.execute(
        """
        CREATE FUNCTION am_append_only() RETURNS trigger
        LANGUAGE plpgsql AS $fn$
        BEGIN
            RAISE EXCEPTION
                'state_transition_not_allowed: % is an append-only ledger; % is refused',
                TG_TABLE_NAME, TG_OP
                USING ERRCODE = 'AM002',
                      HINT = 'Append a new event. A recorded event is never rewritten '
                             'or removed, and the current value is a projection over '
                             'the stream.';
        END
        $fn$;
        """
    )

    # Immutable row: written once, never rewritten. Used for published input state
    # and for emitted evidence.
    op.execute(
        """
        CREATE FUNCTION am_immutable_row() RETURNS trigger
        LANGUAGE plpgsql AS $fn$
        BEGIN
            RAISE EXCEPTION
                'state_transition_not_allowed: % is immutable once written; % is refused',
                TG_TABLE_NAME, TG_OP
                USING ERRCODE = 'AM003',
                      HINT = 'Correcting data creates a new entity with a new '
                             'identifier; it never rewrites an existing one.';
        END
        $fn$;
        """
    )

    # The state guard. One function, parameterised by machine name and state column,
    # reading the declared topology out of contract_state_transition. There is no
    # permissive default: an edge that is not declared is refused.
    op.execute(
        """
        CREATE FUNCTION am_guard_state_transition() RETURNS trigger
        LANGUAGE plpgsql AS $fn$
        DECLARE
            v_machine text := TG_ARGV[0];
            v_column  text := TG_ARGV[1];
            v_old     text;
            v_new     text;
        BEGIN
            EXECUTE format('SELECT ($1).%I', v_column) INTO v_new USING NEW;

            IF TG_OP = 'INSERT' THEN
                IF NOT EXISTS (
                    SELECT 1 FROM contract_state_transition
                    WHERE machine = v_machine
                      AND from_state IS NULL
                      AND to_state = v_new
                ) THEN
                    RAISE EXCEPTION
                        'state_transition_not_allowed: % may not be created in state %',
                        v_machine, v_new
                        USING ERRCODE = 'AM001',
                              DETAIL = 'machine=' || v_machine
                                       || ', current_state=<none>, requested_state='
                                       || coalesce(v_new, '<null>'),
                              HINT = 'Only the declared initial state may be inserted.';
                END IF;
                RETURN NEW;
            END IF;

            EXECUTE format('SELECT ($1).%I', v_column) INTO v_old USING OLD;

            IF v_old IS NOT DISTINCT FROM v_new THEN
                RETURN NEW;
            END IF;

            IF NOT EXISTS (
                SELECT 1 FROM contract_state_transition
                WHERE machine = v_machine
                  AND from_state = v_old
                  AND to_state = v_new
            ) THEN
                RAISE EXCEPTION
                    'state_transition_not_allowed: % has no declared transition % -> %',
                    v_machine, v_old, v_new
                    USING ERRCODE = 'AM001',
                          DETAIL = 'machine=' || v_machine
                                   || ', current_state=' || coalesce(v_old, '<null>')
                                   || ', requested_state=' || coalesce(v_new, '<null>'),
                          HINT = 'A terminal aggregate is never reopened. The '
                                 'corrective action is a new aggregate with a new '
                                 'identifier.';
            END IF;

            RETURN NEW;
        END
        $fn$;
        """
    )

    # Frozen columns: an UPDATE may move the state and the derived bookkeeping, and
    # nothing else. A run's frozen input and configuration set is never edited.
    op.execute(
        """
        CREATE FUNCTION am_guard_frozen_columns() RETURNS trigger
        LANGUAGE plpgsql AS $fn$
        DECLARE
            v_column text;
            v_old    text;
            v_new    text;
        BEGIN
            FOREACH v_column IN ARRAY TG_ARGV LOOP
                EXECUTE format('SELECT ($1).%I::text', v_column) INTO v_old USING OLD;
                EXECUTE format('SELECT ($1).%I::text', v_column) INTO v_new USING NEW;
                IF v_old IS DISTINCT FROM v_new THEN
                    RAISE EXCEPTION
                        'state_transition_not_allowed: %.% is frozen at creation and '
                        'may not be changed', TG_TABLE_NAME, v_column
                        USING ERRCODE = 'AM003',
                              HINT = 'A different value is a different entity. '
                                     'Create a new one with a new identifier.';
                END IF;
            END LOOP;
            RETURN NEW;
        END
        $fn$;
        """
    )

    # Write-once columns: NULL may become a value exactly once; a value never changes
    # and never returns to NULL. Blob verification metadata works this way.
    op.execute(
        """
        CREATE FUNCTION am_guard_write_once_columns() RETURNS trigger
        LANGUAGE plpgsql AS $fn$
        DECLARE
            v_column text;
            v_old    text;
            v_new    text;
        BEGIN
            FOREACH v_column IN ARRAY TG_ARGV LOOP
                EXECUTE format('SELECT ($1).%I::text', v_column) INTO v_old USING OLD;
                EXECUTE format('SELECT ($1).%I::text', v_column) INTO v_new USING NEW;
                IF v_old IS NOT NULL AND v_old IS DISTINCT FROM v_new THEN
                    RAISE EXCEPTION
                        'state_transition_not_allowed: %.% is write-once and already '
                        'carries a value', TG_TABLE_NAME, v_column
                        USING ERRCODE = 'AM003',
                              HINT = 'Verified content metadata is immutable. '
                                     'Different bytes are a different blob_id.';
                END IF;
            END LOOP;
            RETURN NEW;
        END
        $fn$;
        """
    )


# ---------------------------------------------------------------------------
# 2. The declared state topology, as data
# ---------------------------------------------------------------------------


def _create_contract_topology() -> None:
    op.execute(
        """
        CREATE TABLE contract_state_transition (
            machine    text NOT NULL,
            from_state text NULL,
            to_state   text NOT NULL,
            CONSTRAINT ck_contract_state_transition_machine
                CHECK (machine IN ('audit_run', 'blob', 'command_idempotency')),
            CONSTRAINT uq_contract_state_transition_edge
                UNIQUE NULLS NOT DISTINCT (machine, from_state, to_state)
        );
        """
    )
    op.execute(
        "COMMENT ON TABLE contract_state_transition IS "
        "'The declared state topology of contracts/domain/v1/state-machines.json for "
        "the three machines PC-01 instantiates. A NULL from_state declares the initial "
        "state - the only state an INSERT may create. Reference data, not a domain "
        "aggregate: no business row references it. A state with no outgoing row is "
        "terminal by construction.';"
    )
    rows = ", ".join(
        "('{machine}', {origin}, '{target}')".format(
            machine=machine,
            origin="NULL" if origin is None else f"'{origin}'",
            target=target,
        )
        for machine, origin, target in STATE_TOPOLOGY
    )
    op.execute(
        f"INSERT INTO contract_state_transition (machine, from_state, to_state) VALUES {rows};"
    )


# ---------------------------------------------------------------------------
# 3. Project, Document, DocumentVersion
# ---------------------------------------------------------------------------


def _create_project_and_documents() -> None:
    op.execute(
        f"""
        CREATE TABLE project (
            project_uid text PRIMARY KEY,
            name        text NOT NULL,
            created_at  timestamptz NOT NULL DEFAULT now(),
            updated_at  timestamptz NOT NULL DEFAULT now(),
            CONSTRAINT ck_project_project_uid_format CHECK ({id_check('project_uid', 'prj')}),
            CONSTRAINT ck_project_name_length CHECK (char_length(name) BETWEEN 1 AND 200)
        );
        """
    )
    op.execute(
        "COMMENT ON COLUMN project.name IS "
        "'Display label chosen by the expert. Not unique, not an identity and never a "
        "foreign key: two projects may legitimately carry the same name.';"
    )

    op.execute(
        f"""
        CREATE TABLE document (
            document_uid        text PRIMARY KEY,
            project_uid         text NOT NULL REFERENCES project (project_uid),
            display_title       text NOT NULL,
            current_version_uid text NULL,
            created_at          timestamptz NOT NULL DEFAULT now(),
            updated_at          timestamptz NOT NULL DEFAULT now(),
            CONSTRAINT ck_document_document_uid_format
                CHECK ({id_check('document_uid', 'doc')}),
            CONSTRAINT ck_document_project_uid_format
                CHECK ({id_check('project_uid', 'prj')}),
            CONSTRAINT ck_document_current_version_uid_format
                CHECK (current_version_uid IS NULL
                       OR {id_check('current_version_uid', 'ver')}),
            CONSTRAINT ck_document_display_title_length
                CHECK (char_length(display_title) BETWEEN 1 AND 400)
        );
        """
    )
    op.execute("CREATE INDEX ix_document_project_uid ON document (project_uid);")
    op.execute(
        "COMMENT ON COLUMN document.display_title IS "
        "'Presentation value. A human sheet or document number is not an identity and "
        "is never a foreign key.';"
    )

    op.execute(
        f"""
        CREATE TABLE document_version (
            version_uid      text PRIMARY KEY,
            document_uid     text NOT NULL REFERENCES document (document_uid),
            version_ordinal  integer NOT NULL,
            state            text NOT NULL DEFAULT 'published',
            source_filename  text NULL,
            media_type       text NOT NULL,
            byte_size        bigint NOT NULL,
            sha256           text NOT NULL,
            page_count       integer NOT NULL,
            published_at     timestamptz NOT NULL DEFAULT now(),
            created_at       timestamptz NOT NULL DEFAULT now(),
            CONSTRAINT ck_document_version_version_uid_format
                CHECK ({id_check('version_uid', 'ver')}),
            CONSTRAINT ck_document_version_document_uid_format
                CHECK ({id_check('document_uid', 'doc')}),
            CONSTRAINT ck_document_version_state CHECK (state = 'published'),
            CONSTRAINT ck_document_version_ordinal CHECK (version_ordinal >= 1),
            CONSTRAINT ck_document_version_byte_size CHECK (byte_size >= 0),
            CONSTRAINT ck_document_version_sha256 CHECK (sha256 {SHA256}),
            CONSTRAINT ck_document_version_page_count
                CHECK (page_count BETWEEN 1 AND 30),
            CONSTRAINT ck_document_version_media_type
                CHECK (media_type = 'application/pdf'),
            CONSTRAINT uq_document_version_document_uid_version_ordinal
                UNIQUE (document_uid, version_ordinal),
            CONSTRAINT uq_document_version_document_uid_version_uid
                UNIQUE (document_uid, version_uid)
        );
        """
    )
    op.execute(
        "COMMENT ON COLUMN document_version.version_ordinal IS "
        "'Display and ordering value only: v1, v2, v3 as a reviewer reads them. The "
        "contract lists a display ordinal among the non-identities, so nothing in this "
        "schema references it - grep for foreign keys and you will find none. It is "
        "unique per document so version-ordering misuse is detectable at ingest.';"
    )
    op.execute(
        "COMMENT ON COLUMN document_version.source_filename IS "
        "'The uploaded file name, retained for display. Explicitly not an identity: it "
        "is nullable, not unique and referenced by nothing.';"
    )
    op.execute(
        "COMMENT ON COLUMN document_version.page_count IS "
        "'Bounded by the PC-01 input envelope: at most 30 pages. An over-page-count "
        "file is refused by the admission probe with validation_failed before it "
        "reaches this table; the CHECK is the backstop, not the message.';"
    )
    op.execute(
        "COMMENT ON TABLE document_version IS "
        "'A published DocumentVersion is immutable. UPDATE and DELETE are refused by "
        "trigger; a corrected source file creates a new version_uid. PC-01 has no "
        "Import aggregate, so a version row exists only in the published state.';"
    )

    # Closes the cycle: a document points at one of *its own* versions. The composite
    # reference makes pointing at another document's version impossible rather than
    # merely wrong.
    op.execute(
        """
        ALTER TABLE document
            ADD CONSTRAINT fk_document_current_version_document_version
            FOREIGN KEY (document_uid, current_version_uid)
            REFERENCES document_version (document_uid, version_uid);
        """
    )


# ---------------------------------------------------------------------------
# 4. Blob metadata and the immutable input manifest
# ---------------------------------------------------------------------------


def _create_blobs_and_manifest() -> None:
    op.execute(
        f"""
        CREATE TABLE blob (
            blob_id     text PRIMARY KEY,
            state       text NOT NULL DEFAULT 'temporary',
            sha256      text NULL,
            size_bytes  bigint NULL,
            media_type  text NULL,
            created_at  timestamptz NOT NULL DEFAULT now(),
            updated_at  timestamptz NOT NULL DEFAULT now(),
            CONSTRAINT ck_blob_blob_id_format CHECK ({id_check('blob_id', 'blob')}),
            CONSTRAINT ck_blob_state CHECK ({enum_check('state', BLOB_STATES)}),
            CONSTRAINT ck_blob_sha256 CHECK (sha256 IS NULL OR sha256 {SHA256}),
            CONSTRAINT ck_blob_size_bytes CHECK (size_bytes IS NULL OR size_bytes >= 0),
            CONSTRAINT ck_blob_available_is_verified CHECK (
                state <> 'available'
                OR (sha256 IS NOT NULL AND size_bytes IS NOT NULL AND media_type IS NOT NULL)
            )
        );
        """
    )
    # "Re-uploading identical content is idempotent by (sha256, size)". Scoped to
    # available bytes: a rejected or erased blob must not block a later good upload.
    op.execute(
        """
        CREATE UNIQUE INDEX uq_blob_available_content
            ON blob (sha256, size_bytes)
            WHERE state = 'available';
        """
    )
    op.execute(
        "COMMENT ON TABLE blob IS "
        "'Content metadata addressed only by blob_id. There is deliberately no bucket "
        "and no object-key column: the key layout is confined to the S3 adapter, and "
        "the contract lists a bucket name and an object key among the non-identities. "
        "A blob in temporary is never readable by business code and is referenced by "
        "no published manifest.';"
    )
    op.execute(
        "COMMENT ON COLUMN blob.sha256 IS "
        "'Verification value, never an identity and never a foreign key. Write-once: "
        "NULL until verification, then immutable.';"
    )

    op.execute(
        f"""
        CREATE TABLE input_manifest_entry (
            version_uid text NOT NULL REFERENCES document_version (version_uid),
            role        text NOT NULL,
            blob_id     text NOT NULL REFERENCES blob (blob_id),
            sha256      text NOT NULL,
            size_bytes  bigint NOT NULL,
            media_type  text NOT NULL,
            created_at  timestamptz NOT NULL DEFAULT now(),
            CONSTRAINT pk_input_manifest_entry PRIMARY KEY (version_uid, role),
            CONSTRAINT ck_input_manifest_entry_version_uid_format
                CHECK ({id_check('version_uid', 'ver')}),
            CONSTRAINT ck_input_manifest_entry_blob_id_format
                CHECK ({id_check('blob_id', 'blob')}),
            CONSTRAINT ck_input_manifest_entry_role
                CHECK (role ~ '^[a-z][a-z0-9_]*(\\.[a-z][a-z0-9_]*)*$'),
            CONSTRAINT ck_input_manifest_entry_sha256 CHECK (sha256 {SHA256}),
            CONSTRAINT ck_input_manifest_entry_size_bytes CHECK (size_bytes >= 0)
        );
        """
    )
    op.execute(
        "COMMENT ON TABLE input_manifest_entry IS "
        "'The immutable input manifest of one published version, one row per contract "
        "role. UPDATE and DELETE are refused by trigger: a published version and its "
        "manifest are frozen together, which is what makes a run reproducible against "
        "an exactly known input set.';"
    )


# ---------------------------------------------------------------------------
# 5. AuditRun, CommandRecord, StageResult, ModelCall
# ---------------------------------------------------------------------------


def _create_runs_and_commands() -> None:
    op.execute(
        f"""
        CREATE TABLE command_record (
            command_id          text PRIMARY KEY,
            command_type        text NOT NULL,
            idempotency_key     text NOT NULL,
            payload_fingerprint text NOT NULL,
            state               text NOT NULL DEFAULT 'in_progress',
            outcome             jsonb NULL,
            error_code          text NULL,
            created_at          timestamptz NOT NULL DEFAULT now(),
            updated_at          timestamptz NOT NULL DEFAULT now(),
            CONSTRAINT ck_command_record_command_id_format
                CHECK ({id_check('command_id', 'cmd')}),
            CONSTRAINT ck_command_record_command_type
                CHECK (command_type ~ '^[a-z][a-z0-9_]{{2,63}}$'),
            CONSTRAINT ck_command_record_idempotency_key
                CHECK (idempotency_key ~ '^[A-Za-z0-9][A-Za-z0-9._:-]{{0,127}}$'),
            CONSTRAINT ck_command_record_payload_fingerprint
                CHECK (payload_fingerprint {SHA256}),
            CONSTRAINT ck_command_record_state
                CHECK ({enum_check('state', COMMAND_STATES)}),
            CONSTRAINT ck_command_record_error_code
                CHECK (error_code IS NULL OR {enum_check('error_code', ERROR_CODES)}),
            CONSTRAINT ck_command_record_failed_has_code
                CHECK (state <> 'failed' OR error_code IS NOT NULL),
            CONSTRAINT ck_command_record_succeeded_has_outcome
                CHECK (state <> 'succeeded' OR outcome IS NOT NULL),
            CONSTRAINT uq_command_record_command_type_idempotency_key
                UNIQUE (command_type, idempotency_key)
        );
        """
    )
    op.execute(
        "COMMENT ON CONSTRAINT uq_command_record_command_type_idempotency_key "
        "ON command_record IS "
        "'A command key is unique per command type. The contract scopes the key to "
        "command type plus authorized subject plus target aggregate; PC-01 has no "
        "authenticated subject, so the subject dimension is deliberately absent and is "
        "recorded as a deferred widening in docs/program/P02_SEAMS.md.';"
    )
    op.execute(
        "COMMENT ON COLUMN command_record.idempotency_key IS "
        "'Client-supplied comparison value. Never interpreted as, converted into or "
        "stored as a system identifier, and a forbidden error-envelope detail key.';"
    )

    op.execute(
        f"""
        CREATE TABLE audit_run (
            run_id              text PRIMARY KEY,
            project_uid         text NOT NULL REFERENCES project (project_uid),
            version_uid         text NOT NULL REFERENCES document_version (version_uid),
            state               text NOT NULL DEFAULT 'created',
            analysis_profile_id text NOT NULL,
            prompt_bundle_id    text NOT NULL,
            norms_snapshot_id   text NULL,
            provider_mode       text NOT NULL,
            frozen_input_digest text NOT NULL,
            command_id          text NULL REFERENCES command_record (command_id),
            terminal_reason     text NULL,
            interrupted_reason  text NULL,
            degradation_set     jsonb NOT NULL DEFAULT '[]'::jsonb,
            created_at          timestamptz NOT NULL DEFAULT now(),
            updated_at          timestamptz NOT NULL DEFAULT now(),
            terminal_at         timestamptz NULL,
            CONSTRAINT ck_audit_run_run_id_format CHECK ({id_check('run_id', 'run')}),
            CONSTRAINT ck_audit_run_project_uid_format
                CHECK ({id_check('project_uid', 'prj')}),
            CONSTRAINT ck_audit_run_version_uid_format
                CHECK ({id_check('version_uid', 'ver')}),
            CONSTRAINT ck_audit_run_analysis_profile_id_format
                CHECK ({id_check('analysis_profile_id', 'ap')}),
            CONSTRAINT ck_audit_run_prompt_bundle_id_format
                CHECK ({id_check('prompt_bundle_id', 'pb')}),
            CONSTRAINT ck_audit_run_norms_snapshot_id_format
                CHECK (norms_snapshot_id IS NULL
                       OR {id_check('norms_snapshot_id', 'ns')}),
            CONSTRAINT ck_audit_run_command_id_format
                CHECK (command_id IS NULL OR {id_check('command_id', 'cmd')}),
            CONSTRAINT ck_audit_run_state CHECK ({enum_check('state', RUN_STATES)}),
            CONSTRAINT ck_audit_run_provider_mode
                CHECK ({enum_check('provider_mode', PROVIDER_MODES)}),
            CONSTRAINT ck_audit_run_frozen_input_digest
                CHECK (frozen_input_digest {SHA256}),
            CONSTRAINT ck_audit_run_terminal_reason
                CHECK (terminal_reason IS NULL
                       OR {enum_check('terminal_reason', ERROR_CODES)}),
            CONSTRAINT ck_audit_run_terminal_at CHECK (
                (state IN ('published', 'partial', 'failed', 'cancelled'))
                = (terminal_at IS NOT NULL)
            ),
            CONSTRAINT ck_audit_run_failed_has_reason
                CHECK (state <> 'failed' OR terminal_reason IS NOT NULL),
            CONSTRAINT ck_audit_run_partial_records_degradation CHECK (
                state <> 'partial' OR jsonb_array_length(degradation_set) > 0
            ),
            CONSTRAINT ck_audit_run_published_is_not_degraded CHECK (
                state <> 'published' OR jsonb_array_length(degradation_set) = 0
            ),
            CONSTRAINT ck_audit_run_degradation_set_is_array
                CHECK (jsonb_typeof(degradation_set) = 'array')
        );
        """
    )
    op.execute("CREATE INDEX ix_audit_run_project_uid ON audit_run (project_uid);")
    op.execute("CREATE INDEX ix_audit_run_version_uid ON audit_run (version_uid);")
    op.execute("CREATE INDEX ix_audit_run_state ON audit_run (state);")
    op.execute(
        "COMMENT ON TABLE audit_run IS "
        "'The business history of one audit execution request. Its success terminal is "
        "published; there is no succeeded state here, because succeeded is a "
        "StageResult status on a different aggregate. PC-01 instantiates no Job and no "
        "Attempt, so this table carries no job_id, attempt_id or execution token, and "
        "the queued -> running and running -> validating guards of the contract are "
        "recorded as unevaluated under OD-24 rather than faked.';"
    )
    op.execute(
        "COMMENT ON COLUMN audit_run.frozen_input_digest IS "
        "'sha256 over the frozen input and configuration set at creation. A comparison "
        "value used to detect a request whose inputs differ from an existing run - "
        "never an identity and never a foreign key.';"
    )
    op.execute(
        "COMMENT ON COLUMN audit_run.norms_snapshot_id IS "
        "'Always NULL in PC-01: no norms snapshot is pinned, and the NormsSnapshot "
        "clause of the created -> queued guard is recorded unevaluated under OD-24. "
        "The column exists so restoring it later is not a schema change.';"
    )
    op.execute(
        "COMMENT ON COLUMN audit_run.interrupted_reason IS "
        "'OD-10: a run left running by a crash is reconciled to the terminal failed "
        "with an explicit interrupted reason. The contract declares no interrupted "
        "state and this schema invents none.';"
    )
    op.execute(
        "COMMENT ON COLUMN audit_run.degradation_set IS "
        "'The explicitly recorded missing or degraded stage set. A partial run must "
        "record a non-empty set and a published run must record an empty one, so a "
        "silent degradation cannot reach the success terminal.';"
    )

    op.execute(
        f"""
        CREATE TABLE stage_result (
            run_id        text NOT NULL REFERENCES audit_run (run_id),
            stage_id      text NOT NULL,
            stage_version text NOT NULL,
            status        text NOT NULL,
            artifacts     jsonb NOT NULL DEFAULT '[]'::jsonb,
            metrics       jsonb NOT NULL DEFAULT '{{}}'::jsonb,
            error         jsonb NULL,
            started_at    timestamptz NULL,
            finished_at   timestamptz NULL,
            created_at    timestamptz NOT NULL DEFAULT now(),
            CONSTRAINT pk_stage_result PRIMARY KEY (run_id, stage_id),
            CONSTRAINT ck_stage_result_run_id_format CHECK ({id_check('run_id', 'run')}),
            CONSTRAINT ck_stage_result_stage_id
                CHECK ({enum_check('stage_id', STAGE_IDS)}),
            CONSTRAINT ck_stage_result_stage_version
                CHECK (stage_version ~ '^[0-9]+\\.[0-9]+\\.[0-9]+$'),
            CONSTRAINT ck_stage_result_status
                CHECK ({enum_check('status', STAGE_STATUSES)}),
            CONSTRAINT ck_stage_result_succeeded_carries_no_error
                CHECK (status <> 'succeeded' OR error IS NULL),
            CONSTRAINT ck_stage_result_non_succeeded_carries_error
                CHECK (status = 'succeeded' OR error IS NOT NULL),
            CONSTRAINT ck_stage_result_skipped_is_empty_and_final CHECK (
                status <> 'skipped'
                OR (jsonb_array_length(artifacts) = 0
                    AND error ->> 'retryable' IS NOT DISTINCT FROM 'false')
            ),
            CONSTRAINT ck_stage_result_artifacts_is_array
                CHECK (jsonb_typeof(artifacts) = 'array'),
            CONSTRAINT ck_stage_result_metrics_is_object
                CHECK (jsonb_typeof(metrics) = 'object'),
            CONSTRAINT ck_stage_result_error_shape CHECK (
                error IS NULL OR (
                    jsonb_typeof(error) = 'object'
                    AND error ? 'code' AND error ? 'message' AND error ? 'retryable'
                    AND error ->> 'code' ~ '^[a-z][a-z0-9_]{{2,63}}$'
                    AND jsonb_typeof(error -> 'retryable') = 'boolean'
                    AND char_length(error ->> 'message') BETWEEN 1 AND 2000
                )
            ),
            CONSTRAINT ck_stage_result_timing
                CHECK (started_at IS NULL OR finished_at IS NULL
                       OR finished_at >= started_at)
        );
        """
    )
    op.execute(
        "COMMENT ON TABLE stage_result IS "
        "'One StageResult per run and stage, conformant to "
        "contracts/analysis/v1/stage-result.schema.json - which requires no attempt "
        "authority, which is why PC-01 can claim conformance to it while publishing no "
        "JobPackage and no ResultPackage. The fail-closed rule of the schema is "
        "enforced here as CHECK constraints: succeeded carries no error, everything "
        "else requires one, and skipped is empty and non-retryable. The error code is "
        "held to the analysis contract pattern, deliberately not to the twenty-code "
        "domain catalog: a stage-internal code is legal here and is mapped to a catalog "
        "code at the trust boundary, per error-codes.json internal_mapping.';"
    )

    op.execute(
        f"""
        CREATE TABLE model_call (
            model_call_id    text PRIMARY KEY,
            run_id           text NOT NULL REFERENCES audit_run (run_id),
            stage_id         text NOT NULL,
            provider         text NOT NULL,
            model_identity   text NOT NULL,
            provider_mode    text NOT NULL,
            parameters       jsonb NOT NULL DEFAULT '{{}}'::jsonb,
            request_sha256   text NOT NULL,
            response_sha256  text NULL,
            input_tokens     integer NULL,
            output_tokens    integer NULL,
            latency_ms       integer NULL,
            cost_micros      bigint NULL,
            status           text NOT NULL,
            error_code       text NULL,
            created_at       timestamptz NOT NULL DEFAULT now(),
            CONSTRAINT ck_model_call_model_call_id_format
                CHECK ({id_check('model_call_id', 'mc')}),
            CONSTRAINT ck_model_call_run_id_format CHECK ({id_check('run_id', 'run')}),
            CONSTRAINT ck_model_call_stage_id CHECK ({enum_check('stage_id', STAGE_IDS)}),
            CONSTRAINT ck_model_call_provider_mode
                CHECK ({enum_check('provider_mode', PROVIDER_MODES)}),
            CONSTRAINT ck_model_call_status CHECK (status IN ('succeeded', 'failed')),
            CONSTRAINT ck_model_call_request_sha256 CHECK (request_sha256 {SHA256}),
            CONSTRAINT ck_model_call_response_sha256
                CHECK (response_sha256 IS NULL OR response_sha256 {SHA256}),
            CONSTRAINT ck_model_call_error_code
                CHECK (error_code IS NULL OR {enum_check('error_code', ERROR_CODES)}),
            CONSTRAINT ck_model_call_failed_has_code
                CHECK (status <> 'failed' OR error_code IS NOT NULL),
            CONSTRAINT ck_model_call_succeeded_has_response
                CHECK (status <> 'succeeded' OR response_sha256 IS NOT NULL),
            CONSTRAINT ck_model_call_cost_micros
                CHECK (cost_micros IS NULL OR cost_micros >= 0),
            CONSTRAINT ck_model_call_tokens CHECK (
                (input_tokens IS NULL OR input_tokens >= 0)
                AND (output_tokens IS NULL OR output_tokens >= 0)
            )
        );
        """
    )
    op.execute("CREATE INDEX ix_model_call_run_id ON model_call (run_id);")
    op.execute(
        "COMMENT ON TABLE model_call IS "
        "'Provenance for one provider call. Immutable once written. It stores request "
        "and response checksums, never the prompt or the response body: both are "
        "forbidden error-envelope detail keys and neither is needed to prove what ran. "
        "provider_mode is what makes a live run distinguishable from a recorded one in "
        "the UI and in the CSV.';"
    )
    op.execute(
        "COMMENT ON COLUMN model_call.cost_micros IS "
        "'Measured cost in millionths of the provider currency unit, as an integer. "
        "Floating point money is not stored. The OD-03 per-run ceiling is enforced by "
        "the stage, which fails with cost_budget_exceeded rather than truncating.';"
    )


# ---------------------------------------------------------------------------
# 6. Finding, FindingObservation, FindingEvidence
# ---------------------------------------------------------------------------


def _create_findings() -> None:
    op.execute(
        f"""
        CREATE TABLE finding (
            finding_uid     text PRIMARY KEY,
            project_uid     text NOT NULL REFERENCES project (project_uid),
            version_uid     text NOT NULL REFERENCES document_version (version_uid),
            allocated_by_run_id text NOT NULL REFERENCES audit_run (run_id),
            category        text NOT NULL,
            created_at      timestamptz NOT NULL DEFAULT now(),
            CONSTRAINT ck_finding_finding_uid_format CHECK ({id_check('finding_uid', 'fnd')}),
            CONSTRAINT ck_finding_project_uid_format CHECK ({id_check('project_uid', 'prj')}),
            CONSTRAINT ck_finding_version_uid_format CHECK ({id_check('version_uid', 'ver')}),
            CONSTRAINT ck_finding_allocated_by_run_id_format
                CHECK ({id_check('allocated_by_run_id', 'run')}),
            CONSTRAINT ck_finding_category
                CHECK ({enum_check('category', FINDING_CATEGORIES)})
        );
        """
    )
    op.execute("CREATE INDEX ix_finding_allocated_by_run_id ON finding (allocated_by_run_id);")
    op.execute("CREATE INDEX ix_finding_version_uid ON finding (version_uid);")
    op.execute(
        "COMMENT ON TABLE finding IS "
        "'The durable semantic issue identity that carries expert history. PC-01 does "
        "no cross-run matching: every run allocates fresh finding_uid values, which is "
        "why allocated_by_run_id is NOT NULL. Restoring carryover later adds a matching "
        "policy, not a column.';"
    )

    op.execute(
        f"""
        CREATE TABLE finding_observation (
            finding_observation_id text PRIMARY KEY,
            run_id              text NOT NULL REFERENCES audit_run (run_id),
            finding_uid         text NULL REFERENCES finding (finding_uid),
            stage_id            text NOT NULL,
            category            text NOT NULL,
            finding_text        text NOT NULL,
            recommendation_text text NOT NULL,
            grounded            boolean NOT NULL,
            ungrounded_reason   text NULL,
            analysis_profile_id text NOT NULL,
            prompt_bundle_id    text NOT NULL,
            model_call_id       text NULL REFERENCES model_call (model_call_id),
            provider_mode       text NOT NULL,
            created_at          timestamptz NOT NULL DEFAULT now(),
            CONSTRAINT ck_finding_observation_id_format
                CHECK ({id_check('finding_observation_id', 'fobs')}),
            CONSTRAINT ck_finding_observation_run_id_format
                CHECK ({id_check('run_id', 'run')}),
            CONSTRAINT ck_finding_observation_finding_uid_format
                CHECK (finding_uid IS NULL OR {id_check('finding_uid', 'fnd')}),
            CONSTRAINT ck_finding_observation_analysis_profile_id_format
                CHECK ({id_check('analysis_profile_id', 'ap')}),
            CONSTRAINT ck_finding_observation_prompt_bundle_id_format
                CHECK ({id_check('prompt_bundle_id', 'pb')}),
            CONSTRAINT ck_finding_observation_model_call_id_format
                CHECK (model_call_id IS NULL OR {id_check('model_call_id', 'mc')}),
            CONSTRAINT ck_finding_observation_stage_id
                CHECK ({enum_check('stage_id', STAGE_IDS)}),
            CONSTRAINT ck_finding_observation_category
                CHECK ({enum_check('category', FINDING_CATEGORIES)}),
            CONSTRAINT ck_finding_observation_provider_mode
                CHECK ({enum_check('provider_mode', PROVIDER_MODES)}),
            CONSTRAINT ck_finding_observation_text_length
                CHECK (char_length(finding_text) BETWEEN 1 AND 4000
                       AND char_length(recommendation_text) BETWEEN 1 AND 4000),
            CONSTRAINT ck_finding_observation_grounding CHECK (
                grounded = (finding_uid IS NOT NULL)
                AND grounded = (ungrounded_reason IS NULL)
            )
        );
        """
    )
    op.execute("CREATE INDEX ix_finding_observation_run_id ON finding_observation (run_id);")
    op.execute(
        "CREATE INDEX ix_finding_observation_finding_uid ON finding_observation (finding_uid);"
    )
    op.execute(
        "COMMENT ON TABLE finding_observation IS "
        "'Immutable evidence emitted by exactly one run. UPDATE and DELETE are refused "
        "by trigger, which is the contract rule that a rerun creates new observations "
        "and never rewrites or removes earlier ones. Rows are written once, at the end "
        "of validating, after the grounding gate has decided.';"
    )
    op.execute(
        "COMMENT ON COLUMN finding_observation.grounded IS "
        "'The grounding gate verdict, and the whole difference between a published "
        "finding and a diagnostic. An ungrounded observation carries no finding_uid, so "
        "it cannot appear in any finding query or in the CSV by construction rather "
        "than by a WHERE clause somebody has to remember.';"
    )
    op.execute(
        "COMMENT ON COLUMN finding_observation.ungrounded_reason IS "
        "'Why the gate rejected the item - quotation absent, quotation on a different "
        "page, span outside the declared block. Present exactly when grounded is "
        "false.';"
    )

    op.execute(
        f"""
        CREATE TABLE finding_evidence (
            finding_observation_id text NOT NULL
                REFERENCES finding_observation (finding_observation_id),
            evidence_ordinal integer NOT NULL,
            page_number      integer NOT NULL,
            quote            text NOT NULL,
            char_start       integer NOT NULL,
            char_end         integer NOT NULL,
            block_id         text NULL,
            created_at       timestamptz NOT NULL DEFAULT now(),
            CONSTRAINT pk_finding_evidence
                PRIMARY KEY (finding_observation_id, evidence_ordinal),
            CONSTRAINT ck_finding_evidence_observation_id_format
                CHECK ({id_check('finding_observation_id', 'fobs')}),
            CONSTRAINT ck_finding_evidence_evidence_ordinal CHECK (evidence_ordinal >= 0),
            CONSTRAINT ck_finding_evidence_page_number CHECK (page_number >= 1),
            CONSTRAINT ck_finding_evidence_quote_length
                CHECK (char_length(quote) BETWEEN 1 AND 2000),
            CONSTRAINT ck_finding_evidence_span
                CHECK (char_start >= 0 AND char_end > char_start),
            CONSTRAINT ck_finding_evidence_span_matches_quote
                CHECK (char_end - char_start = char_length(quote)),
            CONSTRAINT ck_finding_evidence_block_id CHECK (block_id IS NULL OR block_id ~ '^b_[0-9]{{6}}$')
        );
        """
    )
    op.execute(
        "COMMENT ON TABLE finding_evidence IS "
        "'Evidence rows owned by one observation. The contract declares no identifier "
        "for an evidence item, so there is none: evidence is a value collection "
        "addressed through its observation identity, and evidence_ordinal is a position "
        "inside that owning aggregate, never a cross-entity reference. Immutable, like "
        "the observation that owns it.';"
    )
    op.execute(
        "COMMENT ON COLUMN finding_evidence.char_start IS "
        "'Offset into the document-global character sequence of prepared.text_layer, "
        "counted in Unicode code points after the declared normalization. See "
        "docs/program/P02_SEAMS.md section 4 - the grounding gate resolves exactly this "
        "anchor, so a byte or UTF-16 offset here would silently misplace every "
        "quotation containing a non-ASCII character, which in a Russian-language AR "
        "document is all of them.';"
    )
    op.execute(
        "COMMENT ON CONSTRAINT ck_finding_evidence_span_matches_quote ON finding_evidence IS "
        "'The declared span must be exactly as long as the quotation it claims to "
        "locate. This catches a whole class of off-by-one anchor bugs at write time "
        "rather than at grounding time.';"
    )
    op.execute(
        "COMMENT ON COLUMN finding_evidence.block_id IS "
        "'Anchor into one version geometry.block_index artifact, not a contract "
        "identifier and not a foreign key to anything. Nullable: a quotation is "
        "anchored by page and character span first, and the block is a secondary "
        "anchor.';"
    )


# ---------------------------------------------------------------------------
# 7. Append-only ledgers
# ---------------------------------------------------------------------------


def _create_ledgers() -> None:
    op.execute(
        f"""
        CREATE TABLE expert_decision_event (
            decision_id            text PRIMARY KEY,
            sequence_no            bigint GENERATED ALWAYS AS IDENTITY,
            finding_uid            text NOT NULL REFERENCES finding (finding_uid),
            finding_observation_id text NOT NULL
                REFERENCES finding_observation (finding_observation_id),
            event_type             text NOT NULL,
            verdict                text NULL,
            comment                text NULL,
            author_label           text NOT NULL,
            command_id             text NULL REFERENCES command_record (command_id),
            correlation_id         text NULL,
            recorded_at            timestamptz NOT NULL DEFAULT clock_timestamp(),
            CONSTRAINT ck_expert_decision_event_decision_id_format
                CHECK ({id_check('decision_id', 'dec')}),
            CONSTRAINT ck_expert_decision_event_finding_uid_format
                CHECK ({id_check('finding_uid', 'fnd')}),
            CONSTRAINT ck_expert_decision_event_observation_id_format
                CHECK ({id_check('finding_observation_id', 'fobs')}),
            CONSTRAINT ck_expert_decision_event_command_id_format
                CHECK (command_id IS NULL OR {id_check('command_id', 'cmd')}),
            CONSTRAINT ck_expert_decision_event_correlation_id
                CHECK (correlation_id IS NULL
                       OR correlation_id ~ '^[A-Za-z0-9][A-Za-z0-9._:-]{{0,127}}$'),
            CONSTRAINT ck_expert_decision_event_event_type
                CHECK ({enum_check('event_type', DECISION_EVENT_TYPES)}),
            CONSTRAINT ck_expert_decision_event_verdict
                CHECK (verdict IS NULL OR {enum_check('verdict', VERDICTS)}),
            CONSTRAINT ck_expert_decision_event_author_label
                CHECK (char_length(author_label) BETWEEN 1 AND 128),
            CONSTRAINT ck_expert_decision_event_comment_length
                CHECK (comment IS NULL OR char_length(comment) BETWEEN 1 AND 4000),
            -- IS NOT DISTINCT FROM, not =. A CHECK that evaluates to NULL is
            -- SATISFIED in PostgreSQL, so `verdict = 'accepted'` with a NULL verdict
            -- would have let an accept event through carrying no verdict at all.
            CONSTRAINT ck_expert_decision_event_type_verdict_agree CHECK (
                (event_type = 'accept'  AND verdict IS NOT DISTINCT FROM 'accepted')
                OR (event_type = 'reject'  AND verdict IS NOT DISTINCT FROM 'rejected')
                OR (event_type = 'revoke'  AND verdict IS NOT DISTINCT FROM 'pending')
                OR (event_type = 'comment' AND verdict IS NULL AND comment IS NOT NULL)
            )
        );
        """
    )
    op.execute(
        """
        CREATE INDEX ix_expert_decision_event_finding_uid_sequence_no
            ON expert_decision_event (finding_uid, sequence_no);
        """
    )
    op.execute(
        """
        CREATE UNIQUE INDEX uq_expert_decision_event_command_id
            ON expert_decision_event (command_id) WHERE command_id IS NOT NULL;
        """
    )
    op.execute(
        "COMMENT ON TABLE expert_decision_event IS "
        "'The append-only expert decision ledger. UPDATE and DELETE are refused by the "
        "database itself, not by a repository somebody could bypass: there is no row to "
        "overwrite, so a verdict is a projection over this stream and history cannot be "
        "lost. PD-01: correction and revocation append a new decision_id. PC-01 emits "
        "accept, reject and comment; revoke is in the enum so PD-01 stays implementable "
        "without a schema change.';"
    )
    op.execute(
        "COMMENT ON COLUMN expert_decision_event.author_label IS "
        "'OD-12: one configured local reviewer label, persisted server-side with each "
        "event. PC-01 has no authentication, and this column is the honest record of "
        "that - it is a label, not a subject identity, and it authorizes nothing.';"
    )
    op.execute(
        "COMMENT ON COLUMN expert_decision_event.sequence_no IS "
        "'Server-side total order for rebuilding the projection deterministically, "
        "including within one microsecond of recorded_at. The contract lists a database "
        "sequence value exposed to a client among the non-identities, so this column is "
        "never returned by the API and never embedded in a pagination cursor; the "
        "client-visible order is (recorded_at, decision_id).';"
    )
    op.execute(
        "COMMENT ON INDEX uq_expert_decision_event_command_id IS "
        "'One appended event per command record. Replaying a decision command under one "
        "idempotency key appends exactly one event, enforced here rather than trusted "
        "to the handler.';"
    )

    op.execute(
        f"""
        CREATE TABLE audit_event (
            audit_event_id text PRIMARY KEY,
            sequence_no    bigint GENERATED ALWAYS AS IDENTITY,
            event_type     text NOT NULL,
            aggregate_type text NOT NULL,
            aggregate_id   text NOT NULL,
            correlation_id text NULL,
            payload        jsonb NOT NULL DEFAULT '{{}}'::jsonb,
            occurred_at    timestamptz NOT NULL DEFAULT clock_timestamp(),
            CONSTRAINT ck_audit_event_audit_event_id_format
                CHECK ({id_check('audit_event_id', 'evt')}),
            CONSTRAINT ck_audit_event_event_type
                CHECK (event_type ~ '^[a-z][a-z0-9_.]{{2,127}}$'),
            CONSTRAINT ck_audit_event_aggregate_type
                CHECK (aggregate_type ~ '^[A-Za-z][A-Za-z0-9]{{2,63}}$'),
            CONSTRAINT ck_audit_event_aggregate_id
                CHECK (aggregate_id ~ '^[a-z][a-z0-9]{{1,7}}_{ULID_BODY}$'),
            CONSTRAINT ck_audit_event_correlation_id
                CHECK (correlation_id IS NULL
                       OR correlation_id ~ '^[A-Za-z0-9][A-Za-z0-9._:-]{{0,127}}$'),
            CONSTRAINT ck_audit_event_payload_is_object
                CHECK (jsonb_typeof(payload) = 'object')
        );
        """
    )
    op.execute(
        """
        CREATE INDEX ix_audit_event_aggregate_type_aggregate_id
            ON audit_event (aggregate_type, aggregate_id);
        """
    )
    op.execute("CREATE INDEX ix_audit_event_occurred_at ON audit_event (occurred_at);")
    op.execute(
        "COMMENT ON TABLE audit_event IS "
        "'The append-only audit trail. Several contract guards require their transition "
        "to be recorded as an append-only audit event - blob reconciliation, erasure "
        "reversal, command abandonment - and this is where they record it. UPDATE and "
        "DELETE are refused by the database.';"
    )
    op.execute(
        "COMMENT ON COLUMN audit_event.aggregate_id IS "
        "'Any contract identifier, as text. Deliberately not a foreign key: the trail "
        "must survive the row it describes, and an audit entry that a cascade could "
        "delete is not an audit trail.';"
    )


# ---------------------------------------------------------------------------
# 8. The current-verdict projection
# ---------------------------------------------------------------------------


def _create_projection_view() -> None:
    # A view, not a table: "the current verdict is a rebuildable projection over the
    # event stream" is then true by construction, and the test that rebuilds it and
    # compares cannot pass by comparing a cache with itself.
    op.execute(
        """
        CREATE VIEW finding_current_verdict AS
        SELECT
            f.finding_uid,
            COALESCE(v.verdict, 'pending')  AS current_verdict,
            v.decision_id                   AS latest_verdict_decision_id,
            v.recorded_at                   AS latest_verdict_recorded_at,
            c.comment                       AS latest_comment,
            c.decision_id                   AS latest_comment_decision_id,
            l.decision_id                   AS latest_decision_id,
            l.recorded_at                   AS decision_recorded_at,
            COALESCE(n.event_count, 0)      AS decision_event_count
        FROM finding f
        LEFT JOIN LATERAL (
            SELECT e.decision_id, e.verdict, e.recorded_at
            FROM expert_decision_event e
            WHERE e.finding_uid = f.finding_uid AND e.verdict IS NOT NULL
            ORDER BY e.sequence_no DESC
            LIMIT 1
        ) v ON TRUE
        LEFT JOIN LATERAL (
            SELECT e.decision_id, e.comment
            FROM expert_decision_event e
            WHERE e.finding_uid = f.finding_uid AND e.comment IS NOT NULL
            ORDER BY e.sequence_no DESC
            LIMIT 1
        ) c ON TRUE
        LEFT JOIN LATERAL (
            SELECT e.decision_id, e.recorded_at
            FROM expert_decision_event e
            WHERE e.finding_uid = f.finding_uid
            ORDER BY e.sequence_no DESC
            LIMIT 1
        ) l ON TRUE
        LEFT JOIN LATERAL (
            SELECT count(*) AS event_count
            FROM expert_decision_event e
            WHERE e.finding_uid = f.finding_uid
        ) n ON TRUE;
        """
    )
    op.execute(
        "COMMENT ON VIEW finding_current_verdict IS "
        "'The PD-01 projection, defined once here so the API, the CSV and any test "
        "agree by construction. current_verdict is the verdict of the most recent "
        "verdict-bearing event and pending when there is none; a revoke moves it to "
        "pending and never restores a superseded verdict. latest_comment is the comment "
        "of the most recent event carrying one, whatever its type. latest_decision_id "
        "and decision_recorded_at describe the most recent event of any type, so "
        "appending a comment moves them.';"
    )


# ---------------------------------------------------------------------------
# 9. Attach the guards
# ---------------------------------------------------------------------------


def _attach_guards() -> None:
    for table in (
        "document_version",
        "input_manifest_entry",
        "finding_observation",
        "finding_evidence",
        "model_call",
    ):
        op.execute(
            f"""
            CREATE TRIGGER trg_{table}_immutable
                BEFORE UPDATE OR DELETE ON {table}
                FOR EACH ROW EXECUTE FUNCTION am_immutable_row();
            """
        )

    for table in ("expert_decision_event", "audit_event"):
        op.execute(
            f"""
            CREATE TRIGGER trg_{table}_append_only
                BEFORE UPDATE OR DELETE ON {table}
                FOR EACH ROW EXECUTE FUNCTION am_append_only();
            """
        )

    op.execute(
        """
        CREATE TRIGGER trg_audit_run_state_guard
            BEFORE INSERT OR UPDATE ON audit_run
            FOR EACH ROW EXECUTE FUNCTION am_guard_state_transition('audit_run', 'state');
        """
    )
    op.execute(
        """
        CREATE TRIGGER trg_audit_run_frozen_guard
            BEFORE UPDATE ON audit_run
            FOR EACH ROW EXECUTE FUNCTION am_guard_frozen_columns(
                'run_id', 'project_uid', 'version_uid', 'analysis_profile_id',
                'prompt_bundle_id', 'norms_snapshot_id', 'provider_mode',
                'frozen_input_digest', 'created_at');
        """
    )
    op.execute(
        """
        CREATE TRIGGER trg_blob_state_guard
            BEFORE INSERT OR UPDATE ON blob
            FOR EACH ROW EXECUTE FUNCTION am_guard_state_transition('blob', 'state');
        """
    )
    op.execute(
        """
        CREATE TRIGGER trg_blob_write_once_guard
            BEFORE UPDATE ON blob
            FOR EACH ROW EXECUTE FUNCTION am_guard_write_once_columns(
                'sha256', 'size_bytes', 'media_type');
        """
    )
    op.execute(
        """
        CREATE TRIGGER trg_command_record_state_guard
            BEFORE INSERT OR UPDATE ON command_record
            FOR EACH ROW EXECUTE FUNCTION am_guard_state_transition(
                'command_idempotency', 'state');
        """
    )
    op.execute(
        """
        CREATE TRIGGER trg_command_record_frozen_guard
            BEFORE UPDATE ON command_record
            FOR EACH ROW EXECUTE FUNCTION am_guard_frozen_columns(
                'command_id', 'command_type', 'idempotency_key', 'payload_fingerprint');
        """
    )
    # The topology itself is reference data seeded by this migration. Freezing it
    # closes the obvious bypass: inserting an edge and then taking it.
    op.execute(
        """
        CREATE TRIGGER trg_contract_state_transition_immutable
            BEFORE INSERT OR UPDATE OR DELETE ON contract_state_transition
            FOR EACH ROW EXECUTE FUNCTION am_immutable_row();
        """
    )


def downgrade() -> None:
    """Drop the PC-01 schema, leaving the migrated-but-empty P01 baseline.

    Forward-only in practice. ``db/migrations/README.md``: a down file is not a
    substitute for data recovery, and this one destroys every finding, decision and
    audit event in the database. It exists so a *pre-consumer* revert is one command
    on a disposable local database, which is exactly the rollback the task
    specifies - never something to run against a populated one.
    """
    op.execute("DROP VIEW IF EXISTS finding_current_verdict;")
    for table in (
        "audit_event",
        "expert_decision_event",
        "finding_evidence",
        "finding_observation",
        "finding",
        "model_call",
        "stage_result",
        "audit_run",
        "command_record",
        "input_manifest_entry",
        "blob",
    ):
        op.execute(f"DROP TABLE IF EXISTS {table} CASCADE;")
    op.execute("ALTER TABLE document DROP CONSTRAINT IF EXISTS fk_document_current_version_document_version;")
    op.execute("DROP TABLE IF EXISTS document_version CASCADE;")
    op.execute("DROP TABLE IF EXISTS document CASCADE;")
    op.execute("DROP TABLE IF EXISTS project CASCADE;")
    op.execute("DROP TABLE IF EXISTS contract_state_transition CASCADE;")
    for function in (
        "am_guard_write_once_columns",
        "am_guard_frozen_columns",
        "am_guard_state_transition",
        "am_immutable_row",
        "am_append_only",
    ):
        op.execute(f"DROP FUNCTION IF EXISTS {function}();")
