#!/usr/bin/env python3
"""Build the PC-02 field-validation corpus and its ground-truth manifest.

    python3 fixtures/validation/PC-02/build_pc02_corpus.py           # write the corpus
    python3 fixtures/validation/PC-02/build_pc02_corpus.py --check   # verify, write none

`--check` rebuilds every artefact in memory and compares it byte-for-byte with what is
committed, then re-runs every oracle assertion *against the committed files* rather than
against the fresh build. Verifying the thing in your hand and verifying the thing on disk
are different claims, and only the second is what a validation session will consume.

What the build refuses to do - each of these is a guard, and each is shown failing by
`tools/validation/corpus_check.py --self-test`:

*   write if any filler line contains a digit or a placeholder token. This is the guard
    that keeps the ground truth honest. A stray number in boilerplate is a project
    attribute nobody declared, and a model that noticed it would be scored wrong for
    being right;
*   write if any line would overflow the text box or be drawn into the footer band,
    because a reader could then split or merge a quotation;
*   write if a quotation is not a substring of exactly one line on its declared page;
*   write if two quotations anywhere in the corpus are the same string;
*   write if a quotation is not recoverable character-for-character from the text
    extracted back out of the generated bytes, at exactly the pages it declares and no
    others - checked twice, once with the reference extractor and once with an extractor
    that shares no code with the writer;
*   write if a measurable document falls outside the PC-01 envelope;
*   write if a negative fixture violates anything other than the single rule it is named
    for, or if that rule was not actually evaluated;
*   write if the composition leaves the ranges the task fixes: 12-16 measurable
    documents, exactly 5 of them seeded, and 2-4 negative-envelope documents.

Pure standard library plus the already-pinned `pdfplumber` for the independent
cross-check. `docs/program/P02_LOCK.json` pins `pdfplumber` and `pypdf`; the root lock is
a single-writer hotspot this session does not own and nothing here adds to it.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO_ROOT = HERE.parents[2]

# `ar_corpus` is session A4's stdlib PDF writer, TrueType subsetter and extractor. It is
# imported read-only: this task owns none of `tools/fixtures/**`.
sys.path.insert(0, str(REPO_ROOT / "tools" / "fixtures"))
sys.path.insert(0, str(HERE))

from ar_corpus import content as ar_content  # noqa: E402
from ar_corpus import envelope, pdfextract, pdfwrite, ttfsubset  # noqa: E402
from pc02_corpus import content, layout, negatives  # noqa: E402

FONT_ASSET = REPO_ROOT / "tools" / "fixtures" / "assets" / "ARCorpusSans.ttf"
OUT_DIR = REPO_ROOT / "fixtures" / "validation" / "PC-02"
DOC_DIR = OUT_DIR / "documents"
NEGATIVE_DIR = OUT_DIR / "negative"

MANIFEST_NAME = "corpus_manifest.json"
CHECKSUM_NAME = "SHA256SUMS"

MANIFEST_SCHEMA = "pc02-validation-corpus/1"

# The ranges task P4-QA-01 fixes. The seeded count is exact; the control count carries
# the whole range.
MIN_MEASURABLE = 12
MAX_MEASURABLE = 16
SEEDED_DOCUMENTS = 5
MIN_NEGATIVE = 2
MAX_NEGATIVE = 4

_DIGIT = re.compile(r"[0-9]")


class BuildError(RuntimeError):
    """An invariant the corpus is not allowed to be written without."""


def sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def load_font() -> pdfwrite.EmbeddedFont:
    """Build the embedded font from the committed subset, never from a system font."""
    if not FONT_ASSET.is_file():
        raise BuildError(
            f"missing font subset {FONT_ASSET}. It is session A4's committed asset; "
            "this task does not rebuild it."
        )
    raw = FONT_ASSET.read_bytes()
    metrics = ttfsubset.read(raw)
    used = set(content.document_characters())
    outside = sorted(used - set(ar_content.REPERTOIRE))
    if outside:
        raise BuildError(
            "the PC-02 text uses characters outside the declared repertoire: "
            + " ".join(f"U+{ord(c):04X} {c!r}" for c in outside)
        )
    missing = sorted(used - set(metrics.char_to_gid))
    if missing:
        raise BuildError(
            f"the committed font subset has no glyph for {''.join(missing)!r}."
        )
    return pdfwrite.EmbeddedFont(
        font_bytes=raw,
        units_per_em=metrics.units_per_em,
        char_to_gid=metrics.char_to_gid,
        gid_advance=metrics.gid_advance,
        ascent=metrics.ascent,
        descent=metrics.descent,
        cap_height=metrics.cap_height,
        bbox=metrics.bbox,
    )


# --------------------------------------------------------------------------------------
# Independent extraction
# --------------------------------------------------------------------------------------


def independent_pages(data: bytes, scratch: Path) -> tuple[list[str], str]:
    """Extract page text with a reader that shares no code with the writer.

    Session A4's `pdfextract` and `pdfwrite` are separate modules, but they are one
    author's reading of one specification. If both were wrong in the same way, every
    quotation would verify and every downstream measurement would be contaminated
    silently - which is the failure mode this whole corpus exists to avoid. So the
    quotations are also resolved through `pdfplumber`, which is pinned in
    `docs/program/P02_LOCK.json`, and failing that through poppler's `pdftotext`.
    """
    try:
        import pdfplumber  # noqa: PLC0415
    except ImportError:
        pass
    else:
        scratch.mkdir(parents=True, exist_ok=True)
        tmp = scratch / "independent.pdf"
        tmp.write_bytes(data)
        with pdfplumber.open(str(tmp)) as pdf:
            return [page.extract_text() or "" for page in pdf.pages], "pdfplumber"

    scratch.mkdir(parents=True, exist_ok=True)
    tmp = scratch / "independent.pdf"
    txt = scratch / "independent.txt"
    tmp.write_bytes(data)
    result = subprocess.run(
        ["pdftotext", "-enc", "UTF-8", str(tmp), str(txt)],
        capture_output=True, check=False,
    )
    if result.returncode != 0:
        raise BuildError(
            "no independent extractor is available: pdfplumber is not importable and "
            f"pdftotext failed ({result.returncode}). The corpus may not be written "
            "without a second reader, because a quotation verified only by the "
            "extractor its own author wrote is not verified."
        )
    return txt.read_text(encoding="utf-8").split("\f")[:-1], "pdftotext"


# --------------------------------------------------------------------------------------
# Guards
# --------------------------------------------------------------------------------------


def verify_filler_is_inert() -> list[str]:
    """No digit and no placeholder token in any line the corpus did not author as
    ground truth.

    This is the guard that stops the corpus seeding an issue by accident.
    """
    problems: list[str] = []
    for text in content.FILLER:
        if _DIGIT.search(text):
            problems.append(f"filler sentence contains a digit: {text!r}")
        for token in content.PLACEHOLDER_TOKENS:
            if token in text:
                problems.append(
                    f"filler sentence contains placeholder token {token!r}: {text!r}"
                )
    for doc in content.DOCUMENTS:
        for page in doc.pages:
            for line in page.lines:
                if line.role != "filler":
                    continue
                if _DIGIT.search(line.text):
                    problems.append(
                        f"{doc.label} page {page.number}: filler line contains a "
                        f"digit: {line.text!r}"
                    )
                for token in content.PLACEHOLDER_TOKENS:
                    if token in line.text:
                        problems.append(
                            f"{doc.label} page {page.number}: filler line contains "
                            f"placeholder token {token!r}: {line.text!r}"
                        )
    return problems


def verify_source_placement() -> list[str]:
    """Every quotation is a substring of exactly one authored line on its declared
    page."""
    problems: list[str] = []
    for doc in content.DOCUMENTS:
        for owner, page_number, quotation in content.all_quotations(doc):
            if not 1 <= page_number <= len(doc.pages):
                problems.append(
                    f"{owner}: declared page {page_number} is outside {doc.label}, "
                    f"which has {len(doc.pages)} pages"
                )
                continue
            page = doc.pages[page_number - 1]
            hits = [line.text for line in page.lines if quotation in line.text]
            if len(hits) != 1:
                problems.append(
                    f"{owner}: quotation {quotation!r} matches {len(hits)} authored "
                    f"lines on {doc.label} page {page_number}, expected exactly 1"
                )
    return problems


def verify_quotations_unique() -> list[str]:
    """No two ground-truth items anywhere in the corpus share a quotation string.

    Across documents this is not a correctness requirement - each document is analysed on
    its own - but it is an auditing one. A repeated string makes a session record
    ambiguous about which document a moderator was looking at, and two moderators have to
    produce comparable data.
    """
    seen: dict[str, str] = {}
    problems: list[str] = []
    for doc in content.DOCUMENTS:
        for owner, _page, quotation in content.all_quotations(doc):
            key = f"{doc.label}/{owner}"
            if quotation in seen and seen[quotation].split("/")[1] != owner:
                problems.append(
                    f"quotation {quotation!r} is claimed by both {seen[quotation]} "
                    f"and {key}"
                )
            seen.setdefault(quotation, key)
    return problems


def verify_extracted(doc: content.Doc, pages: list[str], reader: str) -> list[str]:
    """The load-bearing check: quotations survive the round trip through the PDF bytes.

    Character-for-character, at exactly the declared pages and nowhere else. The
    "nowhere else" half matters as much as the first: a quotation that also appeared on
    an undeclared page would make the grounding anchor ambiguous, and a finding could
    then be called grounded against a page nobody meant.
    """
    problems: list[str] = []
    if len(pages) != len(doc.pages):
        problems.append(
            f"{doc.label} [{reader}]: extracted {len(pages)} pages, the document "
            f"declares {len(doc.pages)}"
        )
        return problems

    declared: dict[str, set[int]] = {}
    for _owner, page_number, quotation in content.all_quotations(doc):
        declared.setdefault(quotation, set()).add(page_number)

    for quotation, declared_pages in sorted(declared.items()):
        found = {n for n, text in enumerate(pages, start=1) if quotation in text}
        if found != declared_pages:
            problems.append(
                f"{doc.label} [{reader}]: quotation {quotation!r} declared on pages "
                f"{sorted(declared_pages)}, found on pages {sorted(found)}"
            )
    return problems


def verify_envelope(label: str, data: bytes) -> list[str]:
    report = envelope.check(data)
    if report.accepted:
        return []
    return [
        f"{label} violates {r.rule} ({r.status.value}): {r.detail}"
        for r in report.results if r.status is not envelope.Status.PASS
    ]


def verify_negatives(fixtures: list[negatives.NegativeFixture]) -> list[str]:
    """Each negative violates exactly the single rule it is named for."""
    problems: list[str] = []
    for fixture in fixtures:
        report = envelope.check(fixture.data)
        if report.violations != (fixture.violates,):
            problems.append(
                f"{fixture.filename}: expected to violate exactly {fixture.violates}, "
                f"violates {list(report.violations)}"
            )
        if fixture.violates in report.not_evaluated:
            problems.append(
                f"{fixture.filename}: {fixture.violates} was not evaluated at all, so "
                "the fixture proves nothing about it"
            )
    return problems


def verify_composition(fixtures: list[negatives.NegativeFixture]) -> list[str]:
    """The counts the task fixes, asserted rather than assumed."""
    problems: list[str] = []
    measurable = content.DOCUMENTS
    seeded = content.seeded_documents()
    controls = content.control_documents()

    if not MIN_MEASURABLE <= len(measurable) <= MAX_MEASURABLE:
        problems.append(
            f"{len(measurable)} measurable documents, the task fixes "
            f"{MIN_MEASURABLE}-{MAX_MEASURABLE}"
        )
    if len(seeded) != SEEDED_DOCUMENTS:
        problems.append(
            f"{len(seeded)} seeded documents, the task fixes exactly {SEEDED_DOCUMENTS}"
        )
    if len(seeded) + len(controls) != len(measurable):
        problems.append("a measurable document is neither seeded nor a control")
    if not MIN_NEGATIVE <= len(fixtures) <= MAX_NEGATIVE:
        problems.append(
            f"{len(fixtures)} negative-envelope documents, the task fixes "
            f"{MIN_NEGATIVE}-{MAX_NEGATIVE}"
        )

    for doc in seeded:
        if not doc.seeded:
            problems.append(f"{doc.label} is marked seeded but carries no seeded issue")
    for doc in controls:
        if doc.seeded:
            problems.append(
                f"{doc.label} is marked a control but carries {len(doc.seeded)} seeded "
                "issue(s); a control document's findings are all false positives by "
                "construction, so a seeded issue in one would make that untrue"
            )
        if not doc.controls:
            problems.append(
                f"{doc.label} is a control document with no control statements, so it "
                "applies no false-positive pressure and measures nothing"
            )

    for doc in measurable:
        for issue in doc.seeded:
            if issue.category not in (
                content.CATEGORY_CONTRADICTION, content.CATEGORY_PLACEHOLDER
            ):
                problems.append(
                    f"{issue.id}: category {issue.category!r} is not one of the two "
                    "fixed by PROTOTYPE_PROFILE.md section 7.1"
                )
        for control in doc.controls:
            if control.archetype not in content.ARCHETYPES:
                problems.append(
                    f"{control.id}: archetype {control.archetype!r} is not declared"
                )
    return problems


# --------------------------------------------------------------------------------------
# Manifest
# --------------------------------------------------------------------------------------


def _anchor(pages: list[str], page_number: int, quotation: str) -> dict[str, object]:
    """Locate a quotation inside the extracted page text, for the grounding gate."""
    text = pages[page_number - 1]
    offset = text.find(quotation)
    if offset < 0:
        raise BuildError(f"quotation {quotation!r} is not on page {page_number}")
    lines = text.split("\n")
    consumed = 0
    line_index = 0
    for index, line in enumerate(lines):
        if consumed <= offset < consumed + len(line) + 1:
            line_index = index
            break
        consumed += len(line) + 1
    return {
        "page": page_number,
        "quotation": quotation,
        "char_offset_in_page_text": offset,
        "line_index_in_page_text": line_index,
        "line_text": lines[line_index],
    }


def _document_record(doc: content.Doc, data: bytes,
                     pages: list[str]) -> dict[str, object]:
    return {
        "label": doc.label,
        "role": doc.role,
        "provenance": "synthetic",
        "path": f"fixtures/validation/PC-02/documents/{doc.filename}",
        "title_ru": doc.title,
        "summary_ru": doc.summary,
        "sha256": sha256(data),
        "bytes": len(data),
        "pages": len(pages),
        "language": "ru",
        "discipline": "AR",
        "page_text_sha256": [sha256(text.encode("utf-8")) for text in pages],
        "seeded_issue_count": len(doc.seeded),
        "seeded_issues": [
            {
                "id": issue.id,
                "category": issue.category,
                "attribute_ru": issue.attribute,
                "pages": sorted({ev.page for ev in issue.evidence}),
                "summary_ru": issue.summary,
                "why_seeded": issue.why_seeded,
                "evidence": [
                    _anchor(pages, ev.page, ev.quotation) for ev in issue.evidence
                ],
            }
            for issue in doc.seeded
        ],
        "control_count": len(doc.controls),
        "controls": [
            {
                "id": control.id,
                "pages": list(control.pages),
                "quotation": control.quotation,
                "archetype": control.archetype,
                "would_be_false_positive_as": control.would_be_false_positive_as,
                "why_not_an_issue_ru": control.why_not_an_issue,
                "anchors": [
                    _anchor(pages, page, control.quotation) for page in control.pages
                ],
            }
            for control in doc.controls
        ],
    }


def build_manifest(records: list[dict[str, object]],
                   fixtures: list[negatives.NegativeFixture],
                   independent_reader: str) -> dict[str, object]:
    seeded_issue_count = sum(int(r["seeded_issue_count"]) for r in records)
    control_count = sum(int(r["control_count"]) for r in records)
    archetypes_used = sorted({
        c["archetype"] for r in records for c in r["controls"]  # type: ignore[index]
    })
    return {
        "schema": MANIFEST_SCHEMA,
        "checkpoint": "PC-02",
        "task": "P4-QA-01",
        "synthetic": True,
        "notice": (
            "Synthetic corpus. No customer, production or real project bytes, and no "
            "real organisation, address, person or project. Owner decision OD-17 rules "
            "the corpus synthetic-only; every record's provenance is 'synthetic' and "
            "no record is 'anonymized'."
        ),
        "generated_by": "fixtures/validation/PC-02/build_pc02_corpus.py",
        "regenerate": "python3 fixtures/validation/PC-02/build_pc02_corpus.py",
        "verify": (
            ".venv/bin/python tools/validation/corpus_check.py "
            "fixtures/validation/PC-02/corpus_manifest.json"
        ),
        "protocol": "docs/program/validation/PC-02_PROTOCOL.md",
        "session_record_schema": "fixtures/validation/PC-02/session_record.schema.json",
        "text_extraction": (
            "Quotation offsets are into the text of a single page as produced by "
            "tools/fixtures/ar_corpus/pdfextract.py: runs grouped into lines by "
            "baseline, lines top to bottom, joined by a single newline. Every quotation "
            "lies wholly within one line, so any extractor that preserves line content "
            "resolves it identically. Every quotation was additionally resolved with "
            f"{independent_reader}, which shares no code with the writer."
        ),
        "independent_extractor": independent_reader,
        "envelope": {
            "max_bytes": envelope.MAX_BYTES,
            "max_pages": envelope.MAX_PAGES,
            "rules": {rule: envelope.RULE_DESCRIPTIONS[rule] for rule in envelope.RULES},
        },
        "composition": {
            "measurable_documents": len(records),
            "seeded_documents": SEEDED_DOCUMENTS,
            "control_documents": len(records) - SEEDED_DOCUMENTS,
            "seeded_issues": seeded_issue_count,
            "control_statements": control_count,
            "control_archetypes_used": len(archetypes_used),
            "negative_envelope_documents": len(fixtures),
            "note": (
                "Negative-envelope documents are counted separately and are excluded "
                "from every finding denominator and from every gate that counts "
                "measurable documents, G4 included."
            ),
        },
        "categories": [content.CATEGORY_CONTRADICTION, content.CATEGORY_PLACEHOLDER],
        "finding_labels": ["useful", "incorrect", "unclear"],
        "control_archetypes": content.ARCHETYPES,
        "documents": records,
        "negative_envelope_documents": [
            {
                "label": fixture.label,
                "provenance": "synthetic",
                "path": f"fixtures/validation/PC-02/negative/{fixture.filename}",
                "violates_rule": fixture.violates,
                "rule_description": envelope.RULE_DESCRIPTIONS[fixture.violates],
                "sha256": sha256(fixture.data),
                "bytes": len(fixture.data),
                "description_ru": fixture.description,
                "why_it_matters": fixture.why_it_matters,
            }
            for fixture in fixtures
        ],
    }


def manifest_bytes(manifest: dict[str, object]) -> bytes:
    return (
        json.dumps(manifest, ensure_ascii=False, indent=2, sort_keys=False) + "\n"
    ).encode("utf-8")


def checksum_bytes(entries: list[tuple[str, bytes]]) -> bytes:
    lines = [f"{sha256(data)}  {name}" for name, data in entries]
    return ("\n".join(lines) + "\n").encode("utf-8")


# --------------------------------------------------------------------------------------
# Build
# --------------------------------------------------------------------------------------


def build_all(scratch: Path) -> tuple[list[tuple[Path, bytes]], str]:
    """Build every artefact, verifying every invariant before returning anything."""
    font = load_font()

    problems = verify_filler_is_inert()
    if problems:
        raise BuildError(
            "filler prose is not inert, so the corpus would seed an issue nobody "
            "declared:\n  " + "\n  ".join(problems)
        )

    problems = verify_source_placement()
    if problems:
        raise BuildError("quotation placement:\n  " + "\n  ".join(problems))

    problems = verify_quotations_unique()
    if problems:
        raise BuildError("quotation uniqueness:\n  " + "\n  ".join(problems))

    artefacts: list[tuple[Path, bytes]] = []
    records: list[dict[str, object]] = []
    independent_reader = ""
    failures: list[str] = []

    for doc in content.DOCUMENTS:
        data = layout.build(doc, font)
        pages = pdfextract.extract_pages(data)
        failures += verify_extracted(doc, pages, "ar_corpus.pdfextract")
        other_pages, reader = independent_pages(data, scratch)
        independent_reader = reader
        failures += verify_extracted(doc, other_pages, reader)
        failures += verify_envelope(doc.label, data)
        records.append(_document_record(doc, data, pages))
        artefacts.append((DOC_DIR / doc.filename, data))

    if failures:
        raise BuildError(
            "the text layer does not carry the manifest quotations:\n  "
            + "\n  ".join(failures)
        )

    fixtures = negatives.build_all(font)
    problems = verify_negatives(fixtures)
    if problems:
        raise BuildError("negative fixtures:\n  " + "\n  ".join(problems))

    problems = verify_composition(fixtures)
    if problems:
        raise BuildError("corpus composition:\n  " + "\n  ".join(problems))

    manifest = build_manifest(records, fixtures, independent_reader)
    artefacts.append((OUT_DIR / MANIFEST_NAME, manifest_bytes(manifest)))
    artefacts += [(NEGATIVE_DIR / f.filename, f.data) for f in fixtures]

    checksums = checksum_bytes([
        (str(path.relative_to(OUT_DIR)), data) for path, data in sorted(artefacts)
    ])
    artefacts.append((OUT_DIR / CHECKSUM_NAME, checksums))
    return artefacts, independent_reader


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Build the PC-02 validation corpus.")
    parser.add_argument(
        "--check", action="store_true",
        help="verify the committed corpus against a fresh build; write nothing",
    )
    parser.add_argument(
        "--scratch", default=None,
        help="scratch directory for the independent extractor (default: a temp dir)",
    )
    args = parser.parse_args(argv)

    import tempfile

    with tempfile.TemporaryDirectory(prefix="pc02-build-") as tmp:
        scratch = Path(args.scratch) if args.scratch else Path(tmp)
        try:
            artefacts, reader = build_all(scratch)
        except (BuildError, ValueError, KeyError) as exc:
            print(f"FAIL: {exc}", file=sys.stderr)
            return 1

    if args.check:
        failures: list[str] = []
        for path, data in artefacts:
            rel = path.relative_to(REPO_ROOT)
            if not path.is_file():
                failures.append(f"{rel}: missing")
                continue
            committed = path.read_bytes()
            if committed != data:
                failures.append(
                    f"{rel}: committed sha256 {sha256(committed)} "
                    f"({len(committed)} bytes) != rebuilt sha256 {sha256(data)} "
                    f"({len(data)} bytes)"
                )
        if failures:
            print("FAIL: the committed corpus does not match a fresh build:",
                  file=sys.stderr)
            for failure in failures:
                print(f"  {failure}", file=sys.stderr)
            return 1
        print(f"OK  {len(artefacts)} artefacts match a fresh build "
              f"(independent extractor: {reader})")
        return 0

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    DOC_DIR.mkdir(parents=True, exist_ok=True)
    NEGATIVE_DIR.mkdir(parents=True, exist_ok=True)
    for path, data in artefacts:
        path.write_bytes(data)
        print(f"wrote {path.relative_to(REPO_ROOT)}  {sha256(data)}  {len(data)} bytes")
    print(f"independent extractor: {reader}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
